In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt


In [2]:
digits = load_digits()

In [3]:
X = digits.data
y = digits.target

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

### logistic Regression

algoritmo de optimizacion For small datasets, ‘liblinear’ is a good choice,

If the option chosen is ‘ovr’, then a binary problem is fit for each label.

In [6]:
lr = LogisticRegression(solver = 'liblinear', multi_class = 'ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9583333333333334

### SVM

In [7]:
svm = SVC(gamma = 'auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.4777777777777778

### Random Forest

n_estimators : int, default=100

    The number of trees in the forest.

In [8]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9694444444444444

KFold is a cross-validator that divides the dataset into k folds.
Stratified is to ensure that each fold of dataset has the same proportion of observations with a given label.


In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
from sklearn.model_selection import StratifiedKFold

In [11]:
folds = StratifiedKFold(n_splits = 3)

In [12]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [13]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [14]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [15]:
scores_rf

[0.9265442404006677, 0.9415692821368948, 0.9198664440734557]

### cross_val_score function

In [16]:
from sklearn.model_selection import cross_val_score

##### Logistic regression model performance using cross_val_score

In [17]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target, cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

##### svm model performance using cross

In [20]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=10)

array([0.43888889, 0.57777778, 0.46666667, 0.38888889, 0.47222222,
       0.4       , 0.50555556, 0.57541899, 0.55865922, 0.43575419])

##### random forest performance using cross_val_score

In [19]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.92988314, 0.94490818, 0.92487479])